### PR TITLE
made ivy version consistent, some ignores

### PR DESCRIPTION
**Pull request by agatash-ias**

### CODE REVIEW

**Comment by MichealKum** [comment]
:+1:

**Comment by MichealKum** [comment]
does it work before?

**Comment by gd-smalygin** [comment]
:+1:

**Comment by agatash-ias** [comment]
@MichealKum it may work if you have local unstaged ivy 2.0.3 jar. However for new engineer like me it takes some extra time to figure out why build is not working (missing Ant taskdef) and figure how to fix it

**Pull request merged**
